import React, { useState, useEffect } from 'react';
import {
  X, Stethoscope, Copy, Check, Printer, Share2, Plus,
  Trash2, Calendar, FileText, Activity, AlertCircle, Heart
} from 'lucide-react';
import { DoctorSummary } from '../types';
import { api } from '../services/api';

interface DoctorSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DoctorSummaryModal: React.FC<DoctorSummaryModalProps> = ({
  isOpen,
  onClose
}) => {
  const [summary, setSummary] = useState<DoctorSummary | null>(null);
  const [questions, setQuestions] = useState<string[]>([]);
  const [newQuestion, setNewQuestion] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (isOpen) {
      api.getDoctorSummary().then((data) => {
        setSummary(data);
        setQuestions(data.recommended_questions_for_doctor);
      });
    }
  }, [isOpen]);

  if (!isOpen || !summary) return null;

  const handleAddQuestion = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newQuestion.trim()) return;
    setQuestions(prev => [...prev, newQuestion.trim()]);
    setNewQuestion('');
  };

  const handleRemoveQuestion = (idx: number) => {
    setQuestions(prev => prev.filter((_, i) => i !== idx));
  };

  const handleCopyClipboard = () => {
    const formatted = `MOMENT CLINICAL SUMMARY - "SINCE YOUR LAST VISIT"
Generated for: Dr. Priya Raman, MS (OBG), FICOG (Cloudnine Clinic, Bengaluru)
Patient: ${summary.patient_name}
Gestational Age: ${summary.gestational_age} (Due Date: ${summary.due_date})
High Risk Condition: ${summary.high_risk_flags.join(', ')}
Reporting Period: ${summary.since_last_visit_period}

1. LOGGED SYMPTOMS:
${summary.recent_symptoms_summary.map(s => `• ${s.symptom} (Severity: ${s.severity}, Freq: ${s.frequency}, Onset: ${s.onset}) - Notes: ${s.notes}`).join('\n')}

2. MEDICATION ADHERENCE:
• Compliance Rate: ${summary.medication_compliance_rate}
• Missed Doses: ${summary.missed_doses.length > 0 ? summary.missed_doses.join(', ') : 'None'}

3. HEALTH DATA TRENDS:
${Object.entries(summary.health_metrics_trends).map(([k, v]) => `• ${k}: ${v}`).join('\n')}

4. RECENT LABS & SCANS:
${summary.recent_lab_scan_findings.map(f => `• ${f}`).join('\n')}

5. PATIENT QUESTIONS FOR OB-GYN:
${questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

Generated by MOMENT AI Pregnancy Companion on ${summary.generated_at}`;

    navigator.clipboard.writeText(formatted);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4">
      <div className="bg-white rounded-3xl w-full max-w-3xl max-h-[92vh] flex flex-col shadow-modal border border-rose-100 overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="p-5 border-b border-rose-100 bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 text-white flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-2xl bg-moment-500 text-white flex items-center justify-center shadow-md shadow-moment-500/20">
              <Stethoscope className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h3 className="font-extrabold text-white text-lg">Doctor Visit Clinical Summary</h3>
                <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-500/20 text-rose-300 border border-rose-500/30">
                  Pre-Appointment Brief
                </span>
              </div>
              <p className="text-xs text-slate-300">
                "Since Your Last Visit" • Structured Handoff for Dr. Priya Raman
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="w-9 h-9 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 flex items-center justify-center transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-5 sm:p-6 bg-[#FCFAF8] flex-1 overflow-y-auto space-y-6">
          
          {/* Patient Overview Box */}
          <div className="p-4 rounded-2xl bg-white border border-rose-100 shadow-soft grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            <div>
              <span className="text-slate-400 block font-medium">Patient</span>
              <span className="font-bold text-slate-900">{summary.patient_name}</span>
            </div>
            <div>
              <span className="text-slate-400 block font-medium">Gestational Age</span>
              <span className="font-extrabold text-moment-600">{summary.gestational_age}</span>
            </div>
            <div>
              <span className="text-slate-400 block font-medium">Est. Due Date</span>
              <span className="font-bold text-slate-900">{summary.due_date}</span>
            </div>
            <div>
              <span className="text-slate-400 block font-medium">Clinical Flag</span>
              <span className="font-bold text-amber-700">{summary.high_risk_flags[0]}</span>
            </div>
          </div>

          {/* Section: Since Last Visit Symptoms */}
          <div className="bg-white rounded-2xl p-5 border border-rose-100 shadow-soft space-y-3">
            <h4 className="font-extrabold text-slate-900 text-sm flex items-center space-x-2">
              <AlertCircle className="w-4 h-4 text-moment-500" />
              <span>1. Symptoms Logged Since Last Visit ({summary.since_last_visit_period})</span>
            </h4>

            <div className="space-y-2">
              {summary.recent_symptoms_summary.map((s, idx) => (
                <div key={idx} className="p-3 rounded-xl bg-slate-50 border border-slate-200/80 flex items-start justify-between text-xs">
                  <div>
                    <div className="flex items-center space-x-2">
                      <span className="font-bold text-slate-900">{s.symptom}</span>
                      <span className="px-1.5 py-0.2 rounded bg-amber-100 text-amber-800 font-bold text-[10px]">
                        Severity: {s.severity}
                      </span>
                    </div>
                    <p className="text-slate-600 mt-0.5">
                      Pattern: {s.frequency} • Onset: {s.onset}
                    </p>
                    {s.notes && (
                      <p className="text-slate-500 italic mt-0.5">"{s.notes}"</p>
                    )}
                  </div>
                  <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                    s.triage === 'YELLOW' ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'
                  }`}>
                    {s.triage}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Section: Medication Adherence */}
          <div className="bg-white rounded-2xl p-5 border border-rose-100 shadow-soft space-y-3">
            <h4 className="font-extrabold text-slate-900 text-sm flex items-center space-x-2">
              <Activity className="w-4 h-4 text-emerald-600" />
              <span>2. Medication Adherence & Missed Doses</span>
            </h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
              <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200">
                <span className="font-bold text-emerald-900 block">14-Day Compliance Rate</span>
                <span className="text-emerald-700 font-medium">{summary.medication_compliance_rate}</span>
              </div>
              <div className="p-3 rounded-xl bg-amber-50 border border-amber-200">
                <span className="font-bold text-amber-900 block">Reported Missed Doses</span>
                <span className="text-amber-800 font-medium">
                  {summary.missed_doses.length > 0 ? summary.missed_doses.join('; ') : 'No missed doses'}
                </span>
              </div>
            </div>
          </div>

          {/* Section: Health Data Trends */}
          <div className="bg-white rounded-2xl p-5 border border-rose-100 shadow-soft space-y-3">
            <h4 className="font-extrabold text-slate-900 text-sm flex items-center space-x-2">
              <Heart className="w-4 h-4 text-rose-500" />
              <span>3. Wearable & Home Vitals Trends</span>
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
              {Object.entries(summary.health_metrics_trends).map(([key, val]) => (
                <div key={key} className="p-2.5 rounded-xl bg-slate-50 border border-slate-200">
                  <span className="text-slate-500 block font-medium truncate">{key}</span>
                  <span className="font-bold text-slate-900 block mt-0.5">{val}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Section: Recent Labs & Scans */}
          <div className="bg-white rounded-2xl p-5 border border-rose-100 shadow-soft space-y-3">
            <h4 className="font-extrabold text-slate-900 text-sm flex items-center space-x-2">
              <FileText className="w-4 h-4 text-indigo-600" />
              <span>4. Recent Ultrasound Scans & Lab Panels</span>
            </h4>
            <ul className="space-y-1.5 text-xs text-slate-700">
              {summary.recent_lab_scan_findings.map((finding, idx) => (
                <li key={idx} className="p-2 rounded-xl bg-slate-50 border border-slate-200/80 flex items-start space-x-2">
                  <span className="text-indigo-600 font-bold">•</span>
                  <span>{finding}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Section: Editable Questions for Doctor */}
          <div className="bg-white rounded-2xl p-5 border border-rose-100 shadow-soft space-y-3">
            <div className="flex items-center justify-between">
              <h4 className="font-extrabold text-slate-900 text-sm flex items-center space-x-2">
                <FileText className="w-4 h-4 text-teal-600" />
                <span>5. Questions Prepared for Dr. Priya Raman ({questions.length})</span>
              </h4>
              <span className="text-[11px] text-slate-500">Edit or add custom questions</span>
            </div>

            <div className="space-y-2">
              {questions.map((q, idx) => (
                <div key={idx} className="p-2.5 rounded-xl bg-teal-50/50 border border-teal-200/70 flex items-start justify-between text-xs gap-2 group">
                  <div className="flex items-start space-x-2">
                    <span className="font-bold text-teal-700">{idx + 1}.</span>
                    <span className="text-slate-800 font-medium">{q}</span>
                  </div>
                  <button
                    onClick={() => handleRemoveQuestion(idx)}
                    className="text-slate-400 hover:text-red-500 p-1 opacity-0 group-hover:opacity-100 transition-opacity"
                    title="Remove question"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>

            {/* Add question form */}
            <form onSubmit={handleAddQuestion} className="flex items-center space-x-2 pt-2">
              <input
                type="text"
                value={newQuestion}
                onChange={(e) => setNewQuestion(e.target.value)}
                placeholder="Add another question for your appointment..."
                className="flex-1 bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none"
              />
              <button
                type="submit"
                disabled={!newQuestion.trim()}
                className="px-3 py-2 rounded-xl bg-teal-600 hover:bg-teal-700 text-white font-bold text-xs flex items-center space-x-1"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Add</span>
              </button>
            </form>
          </div>

        </div>

        {/* Action Controls Footer */}
        <div className="p-4 bg-slate-100 border-t border-slate-200 flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="text-slate-500">
            Generated {summary.generated_at}
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="px-4 py-2 rounded-xl bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 font-bold flex items-center space-x-1.5 transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Brief</span>
            </button>
            <button
              onClick={handleCopyClipboard}
              className="px-5 py-2 rounded-xl bg-gradient-to-r from-moment-500 to-rose-500 hover:from-moment-600 hover:to-rose-600 text-white font-bold flex items-center space-x-1.5 shadow-sm transition-all"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied Brief!' : 'Copy to Clipboard'}</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
